<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Aethra\Native\*.cs" Link="Native\%(Filename)%(Extension)" />
    <Compile Remove="..\Aethra\Native\AngleD3D11SwapChainContext.cs" />
    <Compile Remove="..\Aethra\Native\AngleSwapChainPanelContext.cs" />
    <Compile Remove="..\Aethra\Native\D3D11SwapChainPanelHost.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Aethra\NativeRuntime\x64\*.dll" Link="NativeRuntime\x64\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
